CREATE TABLE "users" (
  "id" UUID PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "name" VARCHAR NOT NULL,
  "occupation" VARCHAR NOT NULL,
  "email" VARCHAR NOT NULL,
  "passowrd_hash" VARCHAR NOT NULL,
  "avatar_file_name" VARCHAR,
  "role" VARCHAR,
  "token" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "campaigns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" UUID NOT NULL DEFAULT (uuid_generate_v4()),
  "name" VARCHAR NOT NULL,
  "short_description" VARCHAR,
  "description" VARCHAR,
  "goal_amount" INT,
  "current_amount" INT,
  "perks" VARCHAR,
  "backer_count" INT,
  "slug" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "campaign_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "campaign_id" INT NOT NULL,
  "file_name" VARCHAR,
  "is_primary" INT DEFAULT 0,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "campaign_id" INT NOT NULL,
  "user_id" UUID NOT NULL DEFAULT (uuid_generate_v4()),
  "amount" INT NOT NULL,
  "status" VARCHAR,
  "code" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" TIMESTAMP NOT NULL
);

ALTER TABLE "campaigns" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "campaign_images" ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "transactions" ADD CONSTRAINT "fk_campaign_id"
  FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "transactions" ADD CONSTRAINT "fk_user_id"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id");